[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = "build/client"

[dev]
  command = "pnpm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
